### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ghost** [Affonso-Gui/svglabel#5]
@Affonso-Gui @knorth55 
```
db3) home@home-desktop:~/p12/svglabel/examples$ svg2json with-gimp.svg image.jpg
Traceback (most recent call last):
  File "/home/home/anaconda3/envs/db3/bin/svg2json", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/home/p12/svglabel/svg2json", line 10, in <module>
    from svglabel import svg2json
  File "/home/home/p12/svglabel/svglabel.py", line 59
    print 'Wrote to {}'.format(outfile)
          ^
SyntaxError: invalid syntax
```

**Comment by knorth55** [comment]
are you running with python3?
we need to change to `print()` syntax for python 3.
see #6

**Comment by Affonso-Gui** [comment]
@deepseek I just merged the update to use `print()` syntax, could you please check again to see if the problem was solved?

**Comment by ghost** [comment]
I am running python3.
Thanks to you, this issue is now solved. Keep up the good work.
